# Generated by Django 3.2.4 on 2021-06-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('trainid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('trainname', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('totalseats', models.IntegerField()),
                ('filled', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
