# Generated by Django 3.2.4 on 2021-06-07 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0002_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('passanger_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('trainid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.train', verbose_name='TrainID')),
            ],
        ),
    ]
