# Generated by Django 3.2.4 on 2021-06-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0003_auto_20210611_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
