# Generated by Django 3.2.4 on 2021-06-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0003_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='UserID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
