# Generated by Django 3.2.4 on 2021-06-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0005_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(auto_created=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
