# Generated by Django 3.2.4 on 2021-06-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0005_rename_user_appuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
