# Generated by Django 3.2.4 on 2021-06-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0006_auto_20210611_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.CharField(auto_created=True, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
