# Generated by Django 3.2.4 on 2021-06-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0007_auto_20210611_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='user_id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='UserID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
