# Generated by Django 3.2.4 on 2021-06-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0008_auto_20210611_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
