# Generated by Django 3.2.4 on 2021-06-11 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0008_alter_appuser_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='ApUser',
        ),
    ]
