# Generated by Django 3.2.4 on 2021-06-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0010_alter_appuser_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='AppUserdata',
        ),
        migrations.RenameModel(
            old_name='Ticket',
            new_name='Ticketdata',
        ),
    ]
