# Generated by Django 3.2.4 on 2021-06-11 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0010_auto_20210611_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='UserID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('passanger_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('passanger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.appuser', verbose_name='UserID')),
                ('trainid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.train', verbose_name='TrainID')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
