# Generated by Django 3.2.4 on 2021-06-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0011_auto_20210611_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='UserID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='AppUserdata',
        ),
        migrations.RenameModel(
            old_name='Ticketdata',
            new_name='Ticket',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passanger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.appuser', verbose_name='UserID'),
        ),
    ]
