# Generated by Django 3.2.4 on 2021-06-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0013_auto_20210611_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
