# Generated by Django 3.2.4 on 2021-06-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='UserID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('trainid', models.CharField(max_length=10)),
                ('passanger_id', models.CharField(max_length=10)),
                ('passanger_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('journeydate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('trainid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('trainname', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('totalseats', models.IntegerField()),
                ('filled', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('Ticketcost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('nameoncard', models.CharField(max_length=100)),
                ('cvv', models.IntegerField()),
                ('cardno', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
